monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        bikecorp:
            type: stream
            path: "%kernel.logs_dir%/bikecorp.log"
            level: debug
        velovita:
            type: stream
            path: "%kernel.logs_dir%/velovita.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
